#!/bin/bash

nodemon --exec "sh -c 'dub --build=debug -- dustsucker -o sampleout.json; :'" \
        --ext "d,sdl,yaml,json" \
        --watch "../pils" \
        --watch "source" \
        --watch "examples" \
        --watch "dub.sdl" \
        --watch "run"
