#!/bin/bash

# The sh thing ensures the exit code is always 0 and error exit codes do not
# kill nodemon
nodemon --exec "sh -c 'dub --build=debug -- --verbose -i examples/procedures/livingroom.json -o sampleout.json dustsucker; :'" \
        --ext "d,sdl,yaml,json" \
        --watch "../pils" \
        --watch "source" \
        --watch "examples" \
        --watch "dub.sdl" \
        --watch "run"
